<?php
/**
 * @file
 * Code for the Drupal Camp Ottawa Modify Form Feature
 */

use Drupal\Core\Entity;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
 
 /**
 * Implements hook_form_FORM_ID_alter()
 * See https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_form_FORM_ID_alter/8.2.x
 */
function dco_d8_module_form_node_article_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //check if published
  /*
  * Lookup class Node for Drupal 8:
  *    https://api.drupal.org/api/drupal/core!modules!node!src!Entity!Node.php/class/Node/8.2.x
  */
  $node = $form_state->getFormObject()->getEntity();
  $status = $node->isPublished();

  if ($status) {
    $lock_fields = _dco_d8_module_locked_on_publish();
    foreach  ($lock_fields as $field) {
      $form[$field]['#disabled'] = TRUE;
    }
  }
}

/**
 * Locked field when node is published
 */
function _dco_d8_module_locked_on_publish() {
  return array(
    'title',
    'body',
    'field_tags',
    'field_image',    
  );
}
